app: racecar
service: racecar-queue
frameworkVersion: '3'
useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    profile: ruilabs
    region: ap-southeast-1

constructs:
    jobs:
        type: queue
        worker:
            handler: index.consumer
            timeout: 900
            environment:
              SUPABASE_SERVICE_KEY: ${env:SUPABASE_SERVICE_KEY}
              SUPABASE_URL: ${env:SUPABASE_URL}
              JSON_RPC_URL: ${env:JSON_RPC_URL}

plugins:
    - serverless-lift
    - serverless-offline

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

  schedule:
    handler: index.schedule
    events:
      - httpApi:
          method: post
          path: /schedule
