app: racecar
service: racecar-queue
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs20.x
    profile: ruilabs
    region: ap-southeast-1

constructs:
    jobs:
        type: queue
        worker:
            handler: index.consumer

plugins:
    - serverless-lift
    - serverless-offline

package:
  excludeDevDependencies: true
  # patterns:
  #   - "!node_modules/**"
  individually: true

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
