app: racecar
service: racecar-queue
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs20.x
    profile: ruilabs
    region: ap-southeast-1

constructs:
    jobs:
        type: queue
        worker:
            handler: index.consumer
            timeout: 900

plugins:
    - serverless-lift
    - serverless-offline
    - serverless-dotenv-plugin

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

  schedule:
    handler: index.schedule
    events:
      - httpApi:
          method: post
          path: /schedule
      
